language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script: (cargo install rustfmt || true)
script:
  - bash -c 'cargo fmt -- --write-mode=diff && if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo build --features clippy ; else cargo build ; fi'
