[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
name = "xi-tui"
version = "0.1.0"

[dependencies]
clap = "2.26"
error-chain = "0.11"
jsonrpc-core = "7.1"
log = "0.3"
log4rs = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
termion = "1.5"

[dependencies.clippy]
optional = true
version = "*"
