# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  # stdout:
  #   kind: console

  # An appender named "rpc" that writes to a file with a custom pattern encoder
  file-appender:
    kind: file
    path: "xi-tui.log"

# Set the default logging level to "warn" and attach the "rpc" appender to the root
root:
  level: debug
  appenders:
    - file-appender

loggers:
    xi-tui::core:
        level: debug
        appenders:
            - file-appender
    xi-tui::main:
        level: debug
        appenders:
            - file-appender
